import './globals.css';
import JobProvider from './providers/JobProvider';
import QuestionProvider from './providers/QuestionProvider';
import UserDetailsProvider from './providers/UserDetailsProvider';
import FeedbackProvider from './providers/FeedbackProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning={true} className='bg-gradient-to-br from-indigo-400 to-purple-400 dark:bg-gradient-to-br'>
          <UserDetailsProvider>
            <JobProvider>
              <FeedbackProvider>
                <QuestionProvider>{children}</QuestionProvider>
              </FeedbackProvider>
            </JobProvider>
          </UserDetailsProvider>
      </body>
    </html>
  );
}
